<?php

namespace Database\Seeders;

use App\Models\CustomerAccount;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerAccountSeeder extends Seeder
{
    public function run()
    {
        CustomerAccount::insert([
            // Moiz
            [
                'cid' => '1',
                'name' => 'MR. SHAHBAZ MUSTAFA',
                'company' => 'GALAXY MOTORS Drogheda',
                'phone' => '+353 871080098',
                'whatsapp' => '+353 871080098',
                'address' => 'Apt 203 Black B antsean mhargadh greenlanes drogheda co.louth',
                'city' => 'Dublin',
                'country_id' => 7,
                'description' => '',
                'email' => 'galaxymotorsdrogheda@hotmail.com',
                'currency_id' => 2,
                'agent_id' => 2,
            ],
            [
                'cid' => '2',
                'name' => 'Mr kieran sandford',
                'company' => 'kieran sandford motors',
                'phone' => '0877714750',
                'whatsapp' => '+353 877714750',
                'address' => 'kilrush business park dungarvan x35 r920',
                'city' => 'Dublin',
                'country_id' => 7,
                'description' => '',
                'email' => 'galaxymotorsdrogheda@hotmail.com',
                'currency_id' => 2,
                'agent_id' => 2,
            ],
            // Shaheen
            [
                'cid' => '3',
                'name' => 'careem reynold',
                'company' => 'Island View auto care',
                'phone' => '+12687795030',
                'whatsapp' => '+12687795030',
                'address' => 'bucleys village',
                'city' => 'st johns',
                'country_id' => 11,
                'description' => '',
                'email' => 'careemreynolds@gmail.com',
                'currency_id' => 1,
                'agent_id' => 3,
            ],
            [
                'cid' => '4',
                'name' => 'sean peterkin',
                'company' => 'Enigmatic automotive sales and rentals',
                'phone' => '18765393801',
                'whatsapp' => '18765393801',
                'address' => '27 old greenvale road',
                'city' => 'mandeville manchaster',
                'country_id' => 1,
                'description' => '',
                'email' => 'seanpeterkin73@yahoo.com',
                'currency_id' => 1,
                'agent_id' => 3,
            ],
            [
                'cid' => '5',
                'name' => 'Trevor Persaud',
                'company' => 'plantation enterprises',
                'phone' => '5927022746',
                'whatsapp' => '5927022746',
                'address' => 'lot 387, portion 361 block, plantation enterprise',
                'city' => 'georgetown',
                'country_id' => 3,
                'description' => '',
                'email' => 'trevorpersaud2@gmail.com',
                'currency_id' => 1,
                'agent_id' => 3,
            ],
            [
                'cid' => '6',
                'name' => 'omri simpson',
                'company' => 'Simpson car care',
                'phone' => '2687748043',
                'whatsapp' => '2687748043',
                'address' => 'Liberta Village',
                'city' => 'St.Paul',
                'country_id' => 11,
                'description' => 'TOYOTA VITZ RS GS 2014 Grey',
                'email' => 'omrihonda@gmail.com',
                'currency_id' => 1,
                'agent_id' => 3,
            ],
            [
                'cid' => '7',
                'name' => 'Tjone Tonge',
                'company' => 'Antigua public vehicle',
                'phone' => '12687804930',
                'whatsapp' => '12687804930',
                'address' => 'Ffryes Estate',
                'city' => 'St.Marys',
                'country_id' => 11,
                'description' => 'Toyota ractis 2014 white and silver 1300 cc',
                'email' => 'tijontonge99@gmail.com',
                'currency_id' => 1,
                'agent_id' => 3,
            ],
            [
                'cid' => '8',
                'name' => 'rakeish manning',
                'company' => 'solid impac motors ltd',
                'phone' => '18764695649',
                'whatsapp' => '18764695649',
                'address' => '8 bundy lane Old hope road',
                'city' => 'kingston',
                'country_id' => 1,
                'description' => 'toyota raize 2022',
                'email' => 'Solidimpacmotorltd@gmail.com',
                'currency_id' => 1,
                'agent_id' => 3,
            ],
            [
                'cid' => '9',
                'name' => 'damien coomb',
                'company' => '360 Degree Motor by coomb',
                'phone' => '18763461037',
                'whatsapp' => '18763461037',
                'address' => 'lot 3 addisonville. 40 caledonia road maneville manchester',
                'city' => 'mandeville',
                'country_id' => 1,
                'description' => '',
                'email' => '360motorsja@gmail.com',
                'currency_id' => 1,
                'agent_id' => 3,
            ],
            // Jimmy
            [
                'cid' => '10',
                'name' => 'kamran',
                'company' => 'Drift99 Motors Ltd',
                'phone' => '+353894890466',
                'whatsapp' => '+353894890466',
                'address' => 'Unit 6/7 Naas Rd, Business Park, Bushelloaf, Dublin, D22 N7N3',
                'city' => 'dublin',
                'country_id' => 7,
                'description' => '',
                'email' => 'drift99motors@gmail.com',
                'currency_id' => 2,
                'agent_id' => 4,
            ],
            // Fatima
            [
                'cid' => '11',
                'name' => 'MATTHEW WRIGHT',
                'company' => 'ALROBE INTERNATIONAL CORPORATION LTD',
                'phone' => '18765086799',
                'whatsapp' => '18765086799',
                'address' => 'LOT 44 CARACAS AVENUE',
                'city' => 'kingston',
                'country_id' => 1,
                'description' => '',
                'email' => 'BBC@GMAIL.COM',
                'currency_id' => 1,
                'agent_id' => 5,
            ],
            [
                'cid' => '11',
                'name' => 'damion rhoden',
                'company' => 'ACORN SALES AUTO LTD',
                'phone' => '18763335555',
                'whatsapp' => '18763335555',
                'address' => 'LOT 53 WEST TRADE WAY PORTMORE, ST. CATHERINE',
                'city' => 'kingston',
                'country_id' => 1,
                'description' => '',
                'email' => 'acornsalesauto@gmail.com',
                'currency_id' => 1,
                'agent_id' => 5,
            ],
            // Asad
            [
                'cid' => '12',
                'name' => 'MARK AUTO SPARE',
                'company' => 'MARK AUTO SPARE',
                'phone' => '12464379819',
                'whatsapp' => '12462431293',
                'address' => 'BELAIR',
                'city' => 'St.George',
                'country_id' => 4,
                'description' => '',
                'email' => 'BBEST@CAIRBSURF.COM',
                'currency_id' => 1,
                'agent_id' => 6,
            ],
        ]);
    }
}
